### ISSUE TITLE
Login failed for "NearbyFriends" project

### ISSUE THREAD

**Issue by codeeuser** [HMS-Core/hms-nearby-demo#1]
hello,
I tried to work on the sample project. However, I could not proceed to next step because I cannot login successfully. Could you try to help me on this issue.

I/HMSSDK_HmsClient: receive msg status_code:-1, error_code8014, api_name:nearby.putMessage, app_id:102501559|, pkg_name:com.wheref.nearby.friends, session_id:*, transaction_id:102501559essage20200703085439126248911, resolution:null
D/HmsNearbyKit_sdk_PutMessageTaskApiCall: SDK onRecv err code: 8014 status reason: STATUS_MISSING_PERMISSION_ACCESS_COARSE_LOCATION
E/NearbyFriendsActivity: Login failed:
    com.huawei.hms.common.ApiException: 8014: STATUS_MISSING_PERMISSION_ACCESS_COARSE_LOCATION
        at com.huawei.hms.nearby.t0.a(:3)
        at com.huawei.hms.nearby.c1.a(:28)
        at com.huawei.hms.nearby.c1.a(:10)
        at com.huawei.hms.nearby.c1.doExecute(:1)
        at com.huawei.hms.common.internal.TaskApiCall.onResponse(TaskApiCall.java:190)
        at com.huawei.hms.common.internal.HuaweiApiManager$ConnectionManager$1.onCallback(HuaweiApiManager.java:272)
        at com.huawei.hms.common.internal.HmsClient$a.a(HmsClient.java:100)
        at com.huawei.hms.common.internal.HmsClient$a.onComplete(HmsClient.java:122)
        at com.huawei.hms.adapter.BaseAdapter$BaseRequestResultCallback.a(BaseAdapter.java:277)
        at com.huawei.hms.adapter.BaseAdapter$BaseRequestResultCallback.onResult(BaseAdapter.java:252)
        at com.huawei.hms.adapter.BaseAdapter$BaseRequestResultCallback.onResult(BaseAdapter.java:175)
        at com.huawei.hms.support.api.PendingResultImpl$a.b(PendingResultImpl.java:490)
        at com.huawei.hms.support.api.PendingResultImpl$a.handleMessage(PendingResultImpl.java:467)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:213)
        at android.app.ActivityThread.main(ActivityThread.java:8178)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)

**Comment by yczhaocau** [comment]
The possible reason is that HMS Core does not have ACCESS_COARSE_LOCATION permission. 
Need to give HMS Core ACCESS_COARSE_LOCATION permission

**Comment by codeeuser** [comment]
hello,

The existing sample project has already setup the AndroidManifest.xml about the "android.permission.ACCESS_COARSE_LOCATION".  But, it's still has the above error. May I know how to give HMS Core ACCESS_COARSE_LOCATION permission?

**Comment by yczhaocau** [comment]
Settings > Apps > Apps   Search hms

**Comment by codeeuser** [comment]
Solved
